plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.192'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
}

repositories {
    mavenCentral()
    maven { url 'https://maven.neoforged.net/releases' }
    maven { url 'https://cursemaven.com' }
    maven { url 'https://jitpack.io' }
    maven {
        name = "mcef-download"
        url = uri("https://maven.cinemamod.com")
        content { includeGroup("com.cinemamod") }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    // For dependencies needed only at runtime in dev
    localRuntime
}

dependencies {
    // NeoForge platform
    implementation "net.neoforged:neoforge:${neo_version}"

    // Mixin processor
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    // Project dependencies
    implementation "com.cinemamod:mcef-forge:2.1.1-1.21.1"
    localRuntime 'curse.maven:spark-361579:4762301' // Spark profiler at runtime only
    compileOnly 'curse.maven:vivecraft-ops-667903:5843871'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
    // Generate Mixin refmap without mixingradle
    options.compilerArgs += ["-AoutRefMap=webdisplays.refmap.json"]
}

runs {
    client {
        workingDirectory project.file('run/client')
        systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        arguments.addAll '--username', 'Player'
        jvmArguments.addAll '-mixin.config=webdisplays.mixins.json'
    }
    server {
        workingDirectory project.file('run/server')
        systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        arguments.addAll '--nogui'
        jvmArguments.addAll '-mixin.config=webdisplays.mixins.json'
    }
    gameTestServer {
        workingDirectory project.file('run/gametest')
        systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        jvmArguments.addAll '-mixin.config=webdisplays.mixins.json'
    }
    data {
        workingDirectory project.file('run/data')
        arguments.addAll '--mod', mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

jar {
    manifest {
        attributes(
            'Specification-Title': mod_id,
            'Specification-Vendor': 'montoyo',
            'Specification-Version': '1',
            'Implementation-Title': project.name,
            'Implementation-Version': project.version,
            'Implementation-Vendor' : 'montoyo',
            'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
            'MixinConfigs': 'webdisplays.mixins.json'
        )
    }
}

processResources {
    inputs.property 'version', project.version
    filesMatching('META-INF/neoforge.mods.toml') { // use NeoForge toml
        expand(
            'version': project.version,
            'mod_id': mod_id,
            'mod_name': mod_name,
            'mod_authors': mod_authors,
            'mod_description': mod_description,
            'minecraft_version': minecraft_version,
            'minecraft_version_range': minecraft_version_range,
            'neo_version': neo_version,
            'neo_version_range': neo_version_range,
            'loader_version_range': loader_version_range
        )
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
 
