modLoader="javafml" #mandatory

loaderVersion="[1,)" #mandatory

license="MIT"

issueTrackerURL="" #optional

[[mods]] #mandatory

modId="webdisplays" #mandatory

version="2.0.2-1.21.1" #mandatory

displayName="WebDisplays" #mandatory

displayURL="https://github.com/CinemaMod/webdisplays" #optional

logoFile= "" #optional

credits="" #optional

authors="GiantLuigi4, ds58, Mysticpasta1, montoyo, WaterPicker" #optional

description='''
'''

[[dependencies.webdisplays]] #optional
modId="neoforge" #mandatory
type="required" #mandatory
versionRange="[21.1,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.webdisplays]]
modId="minecraft"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.webdisplays]]
modId="mcef"
type="required"
versionRange="[2.0.0, )"
ordering="NONE"
side="BOTH"
